# Generated by Django 5.2.16 on 2026-08-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_ends_at',
            field=models.DateTimeField(blank=True, help_text='ເວລາທີ່ Flash Sale ຈະສິ້ນສຸດ.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ໃສ່ລາຄາຫຼຸດ ຖ້າຢາກໃຫ້ສິນຄ້ານີ້ຂຶ້ນໃນແຖບ Flash Sale.', max_digits=10, null=True),
        ),
    ]
