# Generated by Django 5.2.16 on 2026-08-17 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: [
                apps.get_model("orders", "Order").objects.filter(pk=order.pk).update(
                    order_number=f"ORD-{uuid.uuid4().hex[:10].upper()}"
                )
                for order in apps.get_model("orders", "Order").objects.all()
            ],
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
