# Generated by Django 5.2.16 on 2026-08-17

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_payment_receipt_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default=apps.orders.models.generate_order_number,
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "ຈ່າຍເງິນປາຍທາງ"),
                    ("bank_transfer", "ໂອນຜ່ານທະນາຄານ"),
                    ("qr_payment", "ຊຳລະດ້ວຍ QR"),
                ],
                default="cash_on_delivery",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "ລໍຖ້າການຊຳລະ"),
                    ("paid", "ຊຳລະແລ້ວ"),
                    ("failed", "ຊຳລະບໍ່ສຳເລັດ"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "ລໍຖ້າດຳເນີນການ"),
                    ("paid", "ຊຳລະແລ້ວ"),
                    ("shipping", "ກຳລັງຈັດສົ່ງ"),
                    ("completed", "ສຳເລັດ"),
                    ("cancelled", "ຍົກເລີກ"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
