# Generated by Django 5.2.16 on 2026-08-18 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_shipping_methods(apps, schema_editor):
    ShippingMethod = apps.get_model("orders", "ShippingMethod")
    defaults = (
        ("ຮັບເອງທີ່ຮ້ານ", "0.00", "ນັດຮັບກັບຮ້ານ", 10),
        ("ຈັດສົ່ງໃນນະຄອນ", "20000.00", "1-2 ມື້", 20),
        ("ຈັດສົ່ງຕ່າງແຂວງ", "30000.00", "2-5 ມື້", 30),
    )
    for name, fee, estimated_delivery, sort_order in defaults:
        ShippingMethod.objects.get_or_create(
            name=name,
            defaults={
                "fee": fee,
                "estimated_delivery": estimated_delivery,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_number_alter_order_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_delivery', models.CharField(blank=True, help_text='ເຊັ່ນ: 2-5 ມື້', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ວິທີຈັດສົ່ງ',
                'verbose_name_plural': 'ວິທີຈັດສົ່ງ',
                'ordering': ('sort_order', 'fee', 'name'),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.shippingmethod'),
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'ກຳລັງກະກຽມສິນຄ້າ'), ('shipping', 'ກຳລັງຈັດສົ່ງ'), ('delivered', 'ຈັດສົ່ງແລ້ວ'), ('cancelled', 'ຍົກເລີກ')], default='pending', max_length=20)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ພັດສະດຸ',
                'verbose_name_plural': 'ພັດສະດຸ',
                'ordering': ('-created_at', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('order', 'seller'), name='unique_order_shipment_per_seller')],
            },
        ),
        migrations.RunPython(create_default_shipping_methods, migrations.RunPython.noop),
    ]
