# Generated by Django 5.2.16 on 2026-08-22 04:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_shippingmethod_order_shipping_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'ເປີເຊັນ (%)'), ('fixed', 'ຈຳນວນເງິນຄົງທີ່ (₭)')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='ປ່ອຍວ່າງໄວ້ = ບໍ່ຈຳກັດຈຳນວນຄັ້ງ', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, editable=False)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ຄູປອງສ່ວນຫຼຸດ',
                'verbose_name_plural': 'ຄູປອງສ່ວນຫຼຸດ',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon'),
        ),
    ]
