# Generated by Django 5.2.16 on 2026-08-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_coupon_order_discount_amount_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
