# Generated by Django 5.2.16 on 2026-08-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_seller_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'ລູກຄ້າ'), ('SELLER', 'ຜູ້ຂາຍ'), ('ADMIN', 'ຜູ້ດູແລລະບົບ')], default='CUSTOMER', max_length=20),
        ),
    ]
