# Generated by Django 5.2.16 on 2026-08-25 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bank_account_name_user_bank_account_number_and_more'),
        ('products', '0006_product_sale_ends_at_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='store_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/store_logo/'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('individual', 'ບຸກຄົນ / ຮ້ານຄ້າສ່ວນຕົວ'), ('company', 'ນິຕິບຸກຄົນ / ບໍລິສັດ')], default='individual', max_length=20)),
                ('business_registration_number', models.CharField(blank=True, max_length=100)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='sellers/verification/')),
                ('agreed_seller_agreement', models.BooleanField(default=False)),
                ('agreed_privacy_policy', models.BooleanField(default=False)),
                ('agreed_seller_rules', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'ລໍຖ້າກວດສອບ'), ('reviewing', 'ກຳລັງກວດສອບ'), ('approved', 'ອະນຸມັດແລ້ວ'), ('rejected', 'ປະຕິເສດ')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_seller_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ໃບສະໝັກຜູ້ຂາຍ',
                'verbose_name_plural': 'ໃບສະໝັກຜູ້ຂາຍ',
                'ordering': ('-created_at',),
            },
        ),
    ]
