# Generated by Django 5.2.16 on 2026-09-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_suspended_user_suspended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_token',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
