# Generated by Django 5.2.16 on 2026-08-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ຕະຫຼາດອອນລາຍ', max_length=120)),
                ('tagline', models.CharField(blank=True, default='ຊື້ງ່າຍ ຂາຍສະດວກ ໃນບ່ອນດຽວ', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('is_store_open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ຂໍ້ມູນຮ້ານ',
                'verbose_name_plural': 'ຂໍ້ມູນຮ້ານ',
            },
        ),
    ]
