# Generated by Django 5.2.16 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="bank_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="payment_qr",
            field=models.ImageField(blank=True, null=True, upload_to="store/payment_qr/"),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="transfer_instructions",
            field=models.TextField(blank=True),
        ),
    ]
