# Generated by Django 5.2.16 on 2026-08-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storesettings_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
