"""
Django settings for config project.

Generated by Django 5.2
"""

from pathlib import Path
import environ

# ---------------------------------------------------
# BASE DIRECTORY
# ---------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------
# ENVIRONMENT
# ---------------------------------------------------

env = environ.Env()

environ.Env.read_env(BASE_DIR / ".env")

# ---------------------------------------------------
# SECURITY
# ---------------------------------------------------

SECRET_KEY = env("SECRET_KEY")

DEBUG = env.bool("DEBUG", default=False)
ENVIRONMENT = env("ENVIRONMENT", default="development")
IS_PRODUCTION = ENVIRONMENT == "production"

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# ---------------------------------------------------
# APPLICATIONS
# ---------------------------------------------------

INSTALLED_APPS = [

    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "django.contrib.humanize",

    # django-allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",

    # Local Apps
    "apps.accounts",
    "apps.core",
    "apps.products",
    "apps.cart",
    "apps.orders",
]

# ---------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "allauth.account.middleware.AccountMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",

]

if not DEBUG:
    # WhiteNoise serves collected static assets without needing a separate web server.
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    MIDDLEWARE.insert(2, "apps.core.middleware.ProductionSecurityHeadersMiddleware")

# ---------------------------------------------------
# URLS
# ---------------------------------------------------

ROOT_URLCONF = "config.urls"

# ---------------------------------------------------
# TEMPLATES
# ---------------------------------------------------

TEMPLATES = [

    {

        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [

            BASE_DIR / "templates",

        ],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.cart_count",

            ],

        },

    },

]

# ---------------------------------------------------
# WSGI
# ---------------------------------------------------

WSGI_APPLICATION = "config.wsgi.application"

# ---------------------------------------------------
# DATABASE
# ---------------------------------------------------

# Managed hosts such as Render provide PostgreSQL as one DATABASE_URL.  Keep the
# individual variables as a fallback so local development continues to work.
DATABASE_URL = env("DATABASE_URL", default="")
if DATABASE_URL:
    DATABASES = {"default": env.db_url("DATABASE_URL")}
    DATABASES["default"].update(
        {
            "CONN_MAX_AGE": env.int("DATABASE_CONN_MAX_AGE", default=60),
            "CONN_HEALTH_CHECKS": True,
        }
    )
else:
    DATABASES = {
        "default": {
            "ENGINE": env(
                "DATABASE_ENGINE",
                default="django.db.backends.postgresql",
            ),
            "NAME": env("DATABASE_NAME"),
            "USER": env("DATABASE_USER"),
            "PASSWORD": env("DATABASE_PASSWORD"),
            "HOST": env("DATABASE_HOST"),
            "PORT": env("DATABASE_PORT"),
            "CONN_MAX_AGE": env.int("DATABASE_CONN_MAX_AGE", default=60),
            "CONN_HEALTH_CHECKS": True,
        }
    }

if env.bool("DATABASE_SSL_REQUIRE", default=not DEBUG):
    DATABASES["default"].setdefault("OPTIONS", {})["sslmode"] = "require"

# ---------------------------------------------------
# PASSWORD VALIDATION
# ---------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },

]

# ---------------------------------------------------
# INTERNATIONALIZATION
# ---------------------------------------------------

# Lao copy is written directly in the storefront templates. Keep Django's internal
# locale at English until a compiled Lao gettext catalog is added.
LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Vientiane"

USE_I18N = True

USE_TZ = True

# ---------------------------------------------------
# STATIC FILES
# ---------------------------------------------------

STATIC_URL = "/static/"

STATICFILES_DIRS = [

    BASE_DIR / "static",

]

STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# ---------------------------------------------------
# MEDIA FILES
# ---------------------------------------------------

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# Optional Cloudflare R2 / S3-compatible object storage for uploads in production.
USE_OBJECT_STORAGE = env.bool("USE_OBJECT_STORAGE", default=False)
if USE_OBJECT_STORAGE and not DEBUG:
    STORAGES["default"] = {"BACKEND": "storages.backends.s3.S3Storage"}
    AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL")
    AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="auto")
    AWS_S3_CUSTOM_DOMAIN = env("AWS_S3_CUSTOM_DOMAIN", default="")
    AWS_QUERYSTRING_AUTH = env.bool("AWS_QUERYSTRING_AUTH", default=False)
    AWS_DEFAULT_ACL = None

# Optional Cloudinary storage for uploads — a free-tier alternative to R2/S3 that
# does not require a payment method on file.
USE_CLOUDINARY_STORAGE = env.bool("USE_CLOUDINARY_STORAGE", default=False)
if USE_CLOUDINARY_STORAGE and not DEBUG:
    INSTALLED_APPS += ["cloudinary_storage", "cloudinary"]
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": env("CLOUDINARY_CLOUD_NAME"),
        "API_KEY": env("CLOUDINARY_API_KEY"),
        "API_SECRET": env("CLOUDINARY_API_SECRET"),
    }
    STORAGES["default"] = {"BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage"}

# ---------------------------------------------------
# LOGIN
# ---------------------------------------------------

LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "home"

LOGOUT_REDIRECT_URL = "home"
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@marketplace.local")
SERVER_EMAIL = env("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=10)

# ---------------------------------------------------
# CUSTOM USER MODEL
# ---------------------------------------------------

# ---------------------------------------------------
# AUTHENTICATION BACKENDS
# ---------------------------------------------------

AUTHENTICATION_BACKENDS = [

    "django.contrib.auth.backends.ModelBackend",

    "allauth.account.auth_backends.AuthenticationBackend",

]

AUTH_USER_MODEL = "accounts.User"
SITE_ID = env.int("SITE_ID", default=1)
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------
# DJANGO ALLAUTH
# ---------------------------------------------------

ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["username*", "email*", "password1*", "password2*"]

SOCIALACCOUNT_AUTO_SIGNUP = True
# Initiating sign-in via GET makes a login endpoint easier to trigger from another
# site.  The provider buttons below therefore submit a CSRF-protected POST request.
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_STORE_TOKENS = False

# Keep email authentication disabled by default.  Google is opted in below because
# its OAuth identity token supplies an email only after Google has verified it.
# When that verified email already belongs to a marketplace user, attach the Google
# identity and sign that user in instead of showing an impossible duplicate signup.
# Facebook is deliberately not opted in: its standard Graph API response does not
# assert that the returned email address is verified.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = False
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_ADAPTER = "apps.accounts.social_account_adapter.MarketplaceSocialAccountAdapter"

# Keep OAuth credentials in the host's secret environment variables, never in the
# repository or in the Django admin's SocialApp table.  A provider remains hidden
# from the storefront until both of its credentials have been supplied.
GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET", default="")
FACEBOOK_APP_ID = env("FACEBOOK_APP_ID", default="")
FACEBOOK_APP_SECRET = env("FACEBOOK_APP_SECRET", default="")
GOOGLE_LOGIN_ENABLED = bool(GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET)
FACEBOOK_LOGIN_ENABLED = bool(FACEBOOK_APP_ID and FACEBOOK_APP_SECRET)

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "EMAIL_AUTHENTICATION": True,
    },
    "facebook": {
        "METHOD": "oauth2",
        "SCOPE": ["email", "public_profile"],
        "FIELDS": ["id", "email", "first_name", "last_name", "name", "picture"],
    },
}

if GOOGLE_LOGIN_ENABLED:
    SOCIALACCOUNT_PROVIDERS["google"]["APP"] = {
        "client_id": GOOGLE_CLIENT_ID,
        "secret": GOOGLE_CLIENT_SECRET,
        "key": "",
    }

if FACEBOOK_LOGIN_ENABLED:
    SOCIALACCOUNT_PROVIDERS["facebook"]["APP"] = {
        "client_id": FACEBOOK_APP_ID,
        "secret": FACEBOOK_APP_SECRET,
        "key": "",
    }

# Production browser and transport security.  The hosting platform must terminate HTTPS
# and pass X-Forwarded-Proto when using a reverse proxy.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_HSTS_SECONDS = 31_536_000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # Enable only after the production domain and every required subdomain use HTTPS.
    SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=True)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    X_FRAME_OPTIONS = "DENY"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": env("LOG_LEVEL", default="INFO")},
}
